<a href="https://colab.research.google.com/github/swathiGangireddy29/datasciencelearing/blob/main/HT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import numpy as np
df = pd.read_csv("/content/career_dataset (1).csv")
df

    Candidate_ID          Name    Age  ...  Skills       City  Applied_Date
0            101    Ravi Kumar   22.0  ...  Python  Hyderabad    01-01-2025
1            102  Priya Sharma   24.0  ...    Java     Mumbai    05-01-2025
2            103           NaN   23.0  ...  Python      Delhi    10-01-2025
3            104    Anil Reddy   25.0  ...     SQL    Chennai    15-01-2025
4            105         Kiran    NaN  ...  Python  Bangalore    20-01-2025
5            106     Sita Devi   24.0  ...    Java  Hyderabad    25-01-2025
6            107         Rahul   26.0  ...  Python     Mumbai    01-02-2025
7            108           Anu  150.0  ...  Python        NaN    05-02-2025
8            109         Vijay   23.0  ...     SQL      Delhi    10-02-2025
9            110         Meena   24.0  ...    Java    Chennai    15-02-2025
10           111         Arjun   22.0  ...  Python  Hyderabad    20-02-2025
11           112         Sneha   25.0  ...    Java     Mumbai    25-02-2025
12           113         Kavya   27.0  ...     SQL      Delhi    01-03-2025
13           114        Rajesh   26.0  ...  Python    Chennai    05-03-2025
14           115         Pooja   24.0  ...     SQL  Bangalore    10-03-2025
15           116         Manoj   23.0  ...    Java  Hyderabad    15-03-2025
16           117         Akhil   22.0  ...  Python     Mumbai    20-03-2025
17           118         Divya   25.0  ...    Java      Delhi    25-03-2025
18           119           NaN   26.0  ...     SQL    Chennai    01-04-2025
19           120        Ramesh   -5.0  ...  Python  Bangalore    05-04-2025
20           103           NaN   23.0  ...  Python      Delhi    10-01-2025
21           106     Sita Devi   24.0  ...    Java  Hyderabad    25-01-2025

[22 rows x 10 columns]

In [5]:
df.head()

   Candidate_ID          Name   Age  ...  Skills       City  Applied_Date
0           101    Ravi Kumar  22.0  ...  Python  Hyderabad    01-01-2025
1           102  Priya Sharma  24.0  ...    Java     Mumbai    05-01-2025
2           103           NaN  23.0  ...  Python      Delhi    10-01-2025
3           104    Anil Reddy  25.0  ...     SQL    Chennai    15-01-2025
4           105         Kiran   NaN  ...  Python  Bangalore    20-01-2025

[5 rows x 10 columns]

In [6]:
df.tail()

    Candidate_ID       Name   Age  ...  Skills       City  Applied_Date
17           118      Divya  25.0  ...    Java      Delhi    25-03-2025
18           119        NaN  26.0  ...     SQL    Chennai    01-04-2025
19           120     Ramesh  -5.0  ...  Python  Bangalore    05-04-2025
20           103        NaN  23.0  ...  Python      Delhi    10-01-2025
21           106  Sita Devi  24.0  ...    Java  Hyderabad    25-01-2025

[5 rows x 10 columns]

In [7]:
df.shape

(22, 10)

In [8]:
df.columns

Index(['Candidate_ID', 'Name', 'Age', 'Gender', 'Qualification',
       'Experience_Years', 'Expected_Salary', 'Skills', 'City',
       'Applied_Date'],
      dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Candidate_ID      22 non-null     int64
 1   Name              19 non-null     object
 2   Age               21 non-null     float64
 3   Gender            21 non-null     object
 4   Qualification     20 non-null     object
 5   Experience_Years  20 non-null     float64
 6   Expected_Salary   21 non-null     float64
 7   Skills            22 non-null     object
 8   City              21 non-null     object
 9   Applied_Date      22 non-null     object
dtypes: float64(3), int64(1), object(6)
memory usage: 1.8+ KB

In [10]:
df.select_dtypes(include = ["int64" , "float64"]
                 ).columns

Index(['Candidate_ID', 'Age', 'Experience_Years', 'Expected_Salary'], dtype='object')

In [11]:
#categorical columns
df.select_dtypes(include=["object"]).columns

Index(['Name', 'Gender', 'Qualification', 'Skills', 'City', 'Applied_Date'], dtype='object')

In [12]:
df.isnull().sum()

Candidate_ID        0
Name                3
Age                 1
Gender              1
Qualification       2
Experience_Years    2
Expected_Salary     1
Skills              0
City                1
Applied_Date        0
dtype: int64

In [13]:
df.columns

Index(['Candidate_ID', 'Name', 'Age', 'Gender', 'Qualification',
       'Experience_Years', 'Expected_Salary', 'Skills', 'City',
       'Applied_Date'],
      dtype='object')

In [15]:
df["Name"] = df["Name"].fillna("Unknown")
df["Age"] = df["Age"].fillna(df["Age"].mean())
df["Gender"] = df["Gender"].fillna(df["Gender"].mode()[0])
df["Qualification"] = df["Qualification"].fillna(df["Qualification"].mode()[0])
df["Experience_Years"] = df["Experience_Years"].fillna(df["Experience_Years"].median())
df["Expected_Salary"] = df["Expected_Salary"].fillna(df["Expected_Salary"].median())
df["City"] = df["City"].fillna(df["City"].mode()[0])

In [16]:
df.isnull().sum()

Candidate_ID        0
Name                0
Age                 0
Gender              0
Qualification       0
Experience_Years    0
Expected_Salary     0
Skills              0
City                0
Applied_Date        0
dtype: int64