<a href="https://colab.research.google.com/github/swathiGangireddy29/datasciencelearing/blob/main/pands.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import pandas as pd

df = pd.DataFrame
df = pd.read_excel("student_dataset_20rows.xlsx")

In [8]:
print(df)

    Student_ID     Name  Age            Course  Marks         City
0          101      Ram   25            Pandas     90   Vijayawada
1          102     Ravi   23             NumPy     81    Hyderabad
2          103     Sita   21            Python     80      Chennai
3          104    Kiran   21      Data Science     98    Bangalore
4          105      Anu   20            Pandas     70       Mumbai
5          106    Rahul   22               SQL     82        Delhi
6          107    Sneha   25     Deep Learning     79         Pune
7          108    Arjun   22  Machine Learning     70      Kolkata
8          109    Pooja   20            Python     95        Vizag
9          110   Vikram   20               SQL     72     Tirupati
10         111    Divya   23     Deep Learning     94     Warangal
11         112     Ajay   21            Python     84       Guntur
12         113  Keerthi   21             NumPy     74      Nellore
13         114   Nikhil   22     Deep Learning     99       Kadapa
14         115    Meena   23                AI     81      Kurnool
15         116      Sai   25            Pandas     97       Ongole
16         117  Lavanya   20                AI     72  Rajahmundry
17         118    Rohit   23            Python     70        Eluru
18         119     Teja   25  Machine Learning     90      Khammam
19         120    Priya   22               SQL     78    Nizamabad

In [12]:
df[df["Marks"]<=90]

    Student_ID     Name  Age            Course  Marks         City
0          101      Ram   25            Pandas     90   Vijayawada
1          102     Ravi   23             NumPy     81    Hyderabad
2          103     Sita   21            Python     80      Chennai
4          105      Anu   20            Pandas     70       Mumbai
5          106    Rahul   22               SQL     82        Delhi
6          107    Sneha   25     Deep Learning     79         Pune
7          108    Arjun   22  Machine Learning     70      Kolkata
9          110   Vikram   20               SQL     72     Tirupati
11         112     Ajay   21            Python     84       Guntur
12         113  Keerthi   21             NumPy     74      Nellore
14         115    Meena   23                AI     81      Kurnool
16         117  Lavanya   20                AI     72  Rajahmundry
17         118    Rohit   23            Python     70        Eluru
18         119     Teja   25  Machine Learning     90      Khammam
19         120    Priya   22               SQL     78    Nizamabad

In [13]:
df[df["Marks"]<80]

    Student_ID     Name  Age            Course  Marks         City
4          105      Anu   20            Pandas     70       Mumbai
6          107    Sneha   25     Deep Learning     79         Pune
7          108    Arjun   22  Machine Learning     70      Kolkata
9          110   Vikram   20               SQL     72     Tirupati
12         113  Keerthi   21             NumPy     74      Nellore
16         117  Lavanya   20                AI     72  Rajahmundry
17         118    Rohit   23            Python     70        Eluru
19         120    Priya   22               SQL     78    Nizamabad

In [20]:
df[df["City"]=="Bangalore"]

   Student_ID   Name  Age        Course  Marks       City
3         104  Kiran   21  Data Science     98  Bangalore

In [19]:
df.iloc[0:3,0:3]

   Student_ID  Name  Age
0         101   Ram   25
1         102  Ravi   23
2         103  Sita   21

In [21]:
df.loc[0:2]

   Student_ID  Name  Age  Course  Marks        City
0         101   Ram   25  Pandas     90  Vijayawada
1         102  Ravi   23   NumPy     81   Hyderabad
2         103  Sita   21  Python     80     Chennai

In [22]:
df[df["Marks"]<90]

    Student_ID     Name  Age            Course  Marks         City
1          102     Ravi   23             NumPy     81    Hyderabad
2          103     Sita   21            Python     80      Chennai
4          105      Anu   20            Pandas     70       Mumbai
5          106    Rahul   22               SQL     82        Delhi
6          107    Sneha   25     Deep Learning     79         Pune
7          108    Arjun   22  Machine Learning     70      Kolkata
9          110   Vikram   20               SQL     72     Tirupati
11         112     Ajay   21            Python     84       Guntur
12         113  Keerthi   21             NumPy     74      Nellore
14         115    Meena   23                AI     81      Kurnool
16         117  Lavanya   20                AI     72  Rajahmundry
17         118    Rohit   23            Python     70        Eluru
19         120    Priya   22               SQL     78    Nizamabad

In [24]:
df[df["Age"]<30]

    Student_ID     Name  Age            Course  Marks         City
0          101      Ram   25            Pandas     90   Vijayawada
1          102     Ravi   23             NumPy     81    Hyderabad
2          103     Sita   21            Python     80      Chennai
3          104    Kiran   21      Data Science     98    Bangalore
4          105      Anu   20            Pandas     70       Mumbai
5          106    Rahul   22               SQL     82        Delhi
6          107    Sneha   25     Deep Learning     79         Pune
7          108    Arjun   22  Machine Learning     70      Kolkata
8          109    Pooja   20            Python     95        Vizag
9          110   Vikram   20               SQL     72     Tirupati
10         111    Divya   23     Deep Learning     94     Warangal
11         112     Ajay   21            Python     84       Guntur
12         113  Keerthi   21             NumPy     74      Nellore
13         114   Nikhil   22     Deep Learning     99       Kadapa
14         115    Meena   23                AI     81      Kurnool
15         116      Sai   25            Pandas     97       Ongole
16         117  Lavanya   20                AI     72  Rajahmundry
17         118    Rohit   23            Python     70        Eluru
18         119     Teja   25  Machine Learning     90      Khammam
19         120    Priya   22               SQL     78    Nizamabad

In [25]:
df[(df["Marks"]>25)|(df["Age"]<30)]

    Student_ID     Name  Age            Course  Marks         City
0          101      Ram   25            Pandas     90   Vijayawada
1          102     Ravi   23             NumPy     81    Hyderabad
2          103     Sita   21            Python     80      Chennai
3          104    Kiran   21      Data Science     98    Bangalore
4          105      Anu   20            Pandas     70       Mumbai
5          106    Rahul   22               SQL     82        Delhi
6          107    Sneha   25     Deep Learning     79         Pune
7          108    Arjun   22  Machine Learning     70      Kolkata
8          109    Pooja   20            Python     95        Vizag
9          110   Vikram   20               SQL     72     Tirupati
10         111    Divya   23     Deep Learning     94     Warangal
11         112     Ajay   21            Python     84       Guntur
12         113  Keerthi   21             NumPy     74      Nellore
13         114   Nikhil   22     Deep Learning     99       Kadapa
14         115    Meena   23                AI     81      Kurnool
15         116      Sai   25            Pandas     97       Ongole
16         117  Lavanya   20                AI     72  Rajahmundry
17         118    Rohit   23            Python     70        Eluru
18         119     Teja   25  Machine Learning     90      Khammam
19         120    Priya   22               SQL     78    Nizamabad

In [26]:
df.loc[df["City"]=="Chennai",["Name","Age"]]

   Name  Age
2  Sita   21

In [ ]:
#sorting :arranging data in a particular order
#usually ascending order , descending order
#df.sort_value(by="column name")

In [27]:
df.sort_values(by="Marks")

    Student_ID     Name  Age            Course  Marks         City
7          108    Arjun   22  Machine Learning     70      Kolkata
4          105      Anu   20            Pandas     70       Mumbai
17         118    Rohit   23            Python     70        Eluru
9          110   Vikram   20               SQL     72     Tirupati
16         117  Lavanya   20                AI     72  Rajahmundry
12         113  Keerthi   21             NumPy     74      Nellore
19         120    Priya   22               SQL     78    Nizamabad
6          107    Sneha   25     Deep Learning     79         Pune
2          103     Sita   21            Python     80      Chennai
1          102     Ravi   23             NumPy     81    Hyderabad
14         115    Meena   23                AI     81      Kurnool
5          106    Rahul   22               SQL     82        Delhi
11         112     Ajay   21            Python     84       Guntur
18         119     Teja   25  Machine Learning     90      Khammam
0          101      Ram   25            Pandas     90   Vijayawada
10         111    Divya   23     Deep Learning     94     Warangal
8          109    Pooja   20            Python     95        Vizag
15         116      Sai   25            Pandas     97       Ongole
3          104    Kiran   21      Data Science     98    Bangalore
13         114   Nikhil   22     Deep Learning     99       Kadapa

In [28]:
df.sort_values(by="City")

    Student_ID     Name  Age            Course  Marks         City
3          104    Kiran   21      Data Science     98    Bangalore
2          103     Sita   21            Python     80      Chennai
5          106    Rahul   22               SQL     82        Delhi
17         118    Rohit   23            Python     70        Eluru
11         112     Ajay   21            Python     84       Guntur
1          102     Ravi   23             NumPy     81    Hyderabad
13         114   Nikhil   22     Deep Learning     99       Kadapa
18         119     Teja   25  Machine Learning     90      Khammam
7          108    Arjun   22  Machine Learning     70      Kolkata
14         115    Meena   23                AI     81      Kurnool
4          105      Anu   20            Pandas     70       Mumbai
12         113  Keerthi   21             NumPy     74      Nellore
19         120    Priya   22               SQL     78    Nizamabad
15         116      Sai   25            Pandas     97       Ongole
6          107    Sneha   25     Deep Learning     79         Pune
16         117  Lavanya   20                AI     72  Rajahmundry
9          110   Vikram   20               SQL     72     Tirupati
0          101      Ram   25            Pandas     90   Vijayawada
8          109    Pooja   20            Python     95        Vizag
10         111    Divya   23     Deep Learning     94     Warangal

In [30]:
df.sort_values(by="Marks",ascending=False)

    Student_ID     Name  Age            Course  Marks         City
13         114   Nikhil   22     Deep Learning     99       Kadapa
3          104    Kiran   21      Data Science     98    Bangalore
15         116      Sai   25            Pandas     97       Ongole
8          109    Pooja   20            Python     95        Vizag
10         111    Divya   23     Deep Learning     94     Warangal
18         119     Teja   25  Machine Learning     90      Khammam
0          101      Ram   25            Pandas     90   Vijayawada
11         112     Ajay   21            Python     84       Guntur
5          106    Rahul   22               SQL     82        Delhi
1          102     Ravi   23             NumPy     81    Hyderabad
14         115    Meena   23                AI     81      Kurnool
2          103     Sita   21            Python     80      Chennai
6          107    Sneha   25     Deep Learning     79         Pune
19         120    Priya   22               SQL     78    Nizamabad
12         113  Keerthi   21             NumPy     74      Nellore
9          110   Vikram   20               SQL     72     Tirupati
16         117  Lavanya   20                AI     72  Rajahmundry
7          108    Arjun   22  Machine Learning     70      Kolkata
4          105      Anu   20            Pandas     70       Mumbai
17         118    Rohit   23            Python     70        Eluru

In [31]:
df.sort_values(by=["City","Marks"])

    Student_ID     Name  Age            Course  Marks         City
3          104    Kiran   21      Data Science     98    Bangalore
2          103     Sita   21            Python     80      Chennai
5          106    Rahul   22               SQL     82        Delhi
17         118    Rohit   23            Python     70        Eluru
11         112     Ajay   21            Python     84       Guntur
1          102     Ravi   23             NumPy     81    Hyderabad
13         114   Nikhil   22     Deep Learning     99       Kadapa
18         119     Teja   25  Machine Learning     90      Khammam
7          108    Arjun   22  Machine Learning     70      Kolkata
14         115    Meena   23                AI     81      Kurnool
4          105      Anu   20            Pandas     70       Mumbai
12         113  Keerthi   21             NumPy     74      Nellore
19         120    Priya   22               SQL     78    Nizamabad
15         116      Sai   25            Pandas     97       Ongole
6          107    Sneha   25     Deep Learning     79         Pune
16         117  Lavanya   20                AI     72  Rajahmundry
9          110   Vikram   20               SQL     72     Tirupati
0          101      Ram   25            Pandas     90   Vijayawada
8          109    Pooja   20            Python     95        Vizag
10         111    Divya   23     Deep Learning     94     Warangal