<a href="https://colab.research.google.com/github/swathiGangireddy29/datasciencelearing/blob/main/task9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import seaborn as sns
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [3]:
df = sns.load_dataset('diamonds')
df

       carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [8]:
df.head(5)
df.shape
df.columns
df[['cut', 'color', 'clarity']].dtypes

cut        category
color      category
clarity    category
dtype: object

In [11]:
encoder_cut = OneHotEncoder(sparse_output=False)

cut_encoded = encoder_cut.fit_transform(df[['cut']])

cut_df = pd.DataFrame(
    cut_encoded,
    columns=encoder_cut.get_feature_names_out(['cut'])
)
cut_df

       cut_Fair  cut_Good  cut_Ideal  cut_Premium  cut_Very Good
0           0.0       0.0        1.0          0.0            0.0
1           0.0       0.0        0.0          1.0            0.0
2           0.0       1.0        0.0          0.0            0.0
3           0.0       0.0        0.0          1.0            0.0
4           0.0       1.0        0.0          0.0            0.0
...         ...       ...        ...          ...            ...
53935       0.0       0.0        1.0          0.0            0.0
53936       0.0       1.0        0.0          0.0            0.0
53937       0.0       0.0        0.0          0.0            1.0
53938       0.0       0.0        0.0          1.0            0.0
53939       0.0       0.0        1.0          0.0            0.0

[53940 rows x 5 columns]

In [12]:
encoder_color = OneHotEncoder(sparse_output=False)

color_encoded = encoder_color.fit_transform(df[['color']])

color_df = pd.DataFrame(
    color_encoded,
    columns=encoder_color.get_feature_names_out(['color'])
)
color_df

       color_D  color_E  color_F  color_G  color_H  color_I  color_J
0          0.0      1.0      0.0      0.0      0.0      0.0      0.0
1          0.0      1.0      0.0      0.0      0.0      0.0      0.0
2          0.0      1.0      0.0      0.0      0.0      0.0      0.0
3          0.0      0.0      0.0      0.0      0.0      1.0      0.0
4          0.0      0.0      0.0      0.0      0.0      0.0      1.0
...        ...      ...      ...      ...      ...      ...      ...
53935      1.0      0.0      0.0      0.0      0.0      0.0      0.0
53936      1.0      0.0      0.0      0.0      0.0      0.0      0.0
53937      1.0      0.0      0.0      0.0      0.0      0.0      0.0
53938      0.0      0.0      0.0      0.0      1.0      0.0      0.0
53939      1.0      0.0      0.0      0.0      0.0      0.0      0.0

[53940 rows x 7 columns]

In [13]:
encoder_clarity = OneHotEncoder(sparse_output=False)

clarity_encoded = encoder_clarity.fit_transform(df[['clarity']])

clarity_df = pd.DataFrame(
    clarity_encoded,
    columns=encoder_clarity.get_feature_names_out(['clarity'])
)
clarity_df

,clarity_I1,clarity_IF,clarity_SI1,clarity_SI2,clarity_VS1,clarity_VS2,clarity_VVS1,clarity_VVS2
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
53935,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
53936,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
53937,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
53938,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
53939,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [15]:
df_numeric = df.drop(columns=['cut', 'color', 'clarity'])
final_df = pd.concat([df_numeric, cut_df, color_df, clarity_df], axis=1)
final_df.head()
final_df.shape
final_df.columns

Index(['carat', 'depth', 'table', 'price', 'x', 'y', 'z', 'cut_Fair',
       'cut_Good', 'cut_Ideal', 'cut_Premium', 'cut_Very Good', 'color_D',
       'color_E', 'color_F', 'color_G', 'color_H', 'color_I', 'color_J',
       'clarity_I1', 'clarity_IF', 'clarity_SI1', 'clarity_SI2', 'clarity_VS1',
       'clarity_VS2', 'clarity_VVS1', 'clarity_VVS2'],
      dtype='object')

In [17]:
df_remaining = df.drop(columns=['cut', 'color', 'clarity'])
final_df = pd.concat(
    [df_remaining, cut_df, color_df, clarity_df],
    axis=1
)
final_df.head()
final_df.shape
final_df.columns

Index(['carat', 'depth', 'table', 'price', 'x', 'y', 'z', 'cut_Fair',
       'cut_Good', 'cut_Ideal', 'cut_Premium', 'cut_Very Good', 'color_D',
       'color_E', 'color_F', 'color_G', 'color_H', 'color_I', 'color_J',
       'clarity_I1', 'clarity_IF', 'clarity_SI1', 'clarity_SI2', 'clarity_VS1',
       'clarity_VS2', 'clarity_VVS1', 'clarity_VVS2'],
      dtype='object')